### ISSUE TITLE
thickness

### ISSUE THREAD

**Issue by Stanley0322** [uri-t/cordouan#2]
I want to wonder that the thickness of my sample is about 0.65nm, can the nelly work?
Because I found that when I put this thickness into the code in MATLAB, it doesn't work.

**Comment by uri-t** [comment]
Unfortunately, Nelly does have trouble with particularly thin samples. The issue in these cases is that the number of reflections Nelly has to consider becomes very large, typically resulting in an out of memory error. If that's what you're seeing, it may be best to try a different approach--this may be a case where the Tinkham approximation is appropriate. If you're seeing a different error, please let me know, since in that case it may still be possible to use Nelly for your data.
